config/routes.rb
Nate::Application.routes.draw do




  root to: "home#index"

  resources :biblebooks
  resources :teachings
  resources :users
  resources :sessions
  resources :bios
  resources :abouts
  resources :books
  resources :notes do
    resources :links
  end

  ### All for authentication ###
  get "log_out"  => "sessions#destroy", :as => "log_out"
  get "log_in"   => "sessions#new",     :as => "log_in"
  get "sign_up"  => "users#new",        :as => "sign_up"
  ##############################

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @biblebooks = Biblebook.find(:all, :order => "position ASC")
    @abouts     = About.all #change to only show first?
    @books      = Book.all
    @notes      = Note.all #change to only show first?
    @bios       = Bio.all #change to only show first?
  end

end

app/views/home/_about.html.erb
<div class="one gradi-1">
  <span id="about-link" style="position:absolute;margin-top:-30px;"></span>
  <h1 class="nice-header-2">About Nate</h1>

  <div class="row">
    </br>
    <div class="small-12 large-8 columns">
      <% @abouts.each do |about| %>
        <%= markdown(about.body) %>
    </div>
    <div class="small-12 large-4 columns">
      <div class="nav-buffer show-desktop">&nbsp;</div>
      <%= image_tag about.image.url(:large), class: "show-desktop" %>
      <%= image_tag about.image.url(:medium), class: "show-mobile" %>
      <% end %>
    </div>
  </div>
  <br>
</div>

app/views/home/_admin_links.html.erb
<div id="user">
  <div class="row">
    <div class="small-12 columns">
      <h1>Logged in as <%= current_user.email %></h1>
    </div>
  </div>
  <div class="row">
    <div class="small-12 large-4 columns">
      <h3>&nbsp;</h3>
    </div>
    <div class="small-12 large-4 columns">
      <h3>
        <%= link_to "Teachings", teachings_path %>
        <%= link_to "Biblebooks", biblebooks_path %>
        <%= link_to "Bio", "/bios/1/edit" %>
        <%= link_to "Books", books_path %>
        <%= link_to "Calvary", "/notes/1/edit" %>
        <%= link_to "About", "/abouts/1/edit" %>
        </br>
        </br>
        <%= link_to "Log out", log_out_path %>
      </h3>
    </div>
    <div class="small-12 large-4 columns">
      <h3>&nbsp;</h3>
    </div>
  </div>
</div>

app/views/home/_biblebooks.html.erb
<span id="teachings-link" style="margin-top:-30px;position:absolute;"></span>
<h1 class="nice-header-1">Teachings</h1>
<div class="clearfix">
  <h2 class="hh2" style="color:#ddd;">a through the bible studio series</h2>

  <div class="clearfix" style="max-width: 1200px;">
    <div jc-biblebook></div>
  </div>
</div>

app/views/home/_bios.html.erb
<div class="one gradi-1">
  <div class="row">
    <span id="bio-link" style="position:absolute;top:-85px;"></span>
    <div class="small-12 large-7 columns">
      <% @bios.each do |bio| %>
        <%= markdown(bio.text) %>
        <a href="#" class="about-link">more</a>
        <hr />
        <%= markdown(bio.subtext) %>
        <a href="mailto:pastornate@calvary.com" class="contact-link">pastornate@calvary.com</a>
    </div>

    <div class="small-12 large-4 columns">
      <div class="nav-buffer show-desktop"></div>
      </br>
      <%= image_tag bio.image.url(:medium), class: "show-desktop" %>
      <%= image_tag bio.image.url(:thumb), class: "show-mobile" %>
      <% end %>
    </div>
  </div>
    <br>
    <br>
</div>

app/views/home/_books.html.erb
<div class="one gradi-1">
  <span id="books-link" style="margin-top:-30px;position:absolute;"></span>
  <h1 class="nice-header-2">Books</h1>


<% @books.each do |book| %>
  <div class="row">
    <div class="small-12 large-2 columns show-desktop">
      <div class="nav-buffer">&nbsp;</div>
    </div>
    <div class="small-12 large-6 columns">
        <h2 class="hh2"><%= book.title %></h2>

        <p><%= markdown(book.body) %></p>
    </div>
    </br>
    <div class="small-12 large-4 columns">
      <a class="book-link" href="<%= book.buylink %>"><%= image_tag book.image.url(:medium), class: "br-small show-desktop" %></a>
      <a class="book-link" href="<%= book.buylink %>"><%= image_tag book.image.url(:thumb), class: "show-mobile" %></a>
      <div class="book-buy">
        <h3><a href="<%= book.buylink %>" target="_blank" class="button2">buy here</a></h3>
      </div>
    </div>
  </div>
<% end %>

</div>

app/views/home/_calvary.html.erb
<span id="calvary-link" style="margin-top:-20px;position:absolute;"></span>
<div>

  <br>
  <br class="show-desktop">
  <h1 class="dark"><%= image_tag "calvary_logo.png" %></h1>
  <br class="show-desktop">
  <br class="show-desktop">
  <br>
  <div class="row">

  <div class="large-3 columns show-desktop">

    <div class="icon" style="margin-left:40px;">
      <a href="https://itunes.apple.com/us/app/calvary-monterey/id417437500?mt=8" class="social" target="_blank">
        <i class="footer-icon m-calvary-app"></i>
      </a>
    </div>
    <a href="https://play.google.com/store/apps/details?id=com.subsplash.thechurchapp.calvarymonterey" class="social" target="_blank">
      <div class="icon" style="margin-left:40px;"><i class="footer-icon m-google-play"></i></div>
    </a>

  </div>

  <% @notes.each do |note| %>
    <div class="small-12 large-6 columns">
      <div class="info-box">
        <%= markdown(note.body) %>
      </div>
      <% note.links.each do |link| %>
        </br>
        <h3><%= link_to link.name, link.link, class: "calvary-link" %></h3>
        </br>
      <% end %>
    </div>
  <% end %>

    <div class="large-3 columns show-desktop">
      <a href="http://calvary.com/teaching_topics.php" class="social" target="_blank">
        <div class="icon" style="margin-left:40px;"><i class="footer-icon m-bible"></i></div>
      </a>
      <a href="https://itunes.apple.com/us/podcast/calvary-monterey-audio/id216918040?mt=2&ign-mpt=uo%3D4" class="social" target="_blank">
        <div class="icon" style="margin-left:40px;"><i class="footer-icon m-podcast"></i></div>
      </a>
    </div>



    <!-- mobile links -->
    <div class="small-12 columns show-mobile">
      <div class="m-link-box">
        <a href="https://itunes.apple.com/us/app/calvary-monterey/id417437500?mt=8" class="social" target="_blank">
          <div class="icon"><div class="footer-icon m-calvary-app">&nbsp;</div></div>
        </a>
      </div>
      <div class="m-link-box">
        <a href="https://play.google.com/store/apps/details?id=com.subsplash.thechurchapp.calvarymonterey" class="social" target="_blank">
          <div class="icon"><div class="footer-icon m-google-play">&nbsp;</div></div>
        </a>
      </div>
      <div class="m-link-box">
        <a href="http://calvary.com/teaching_topics.php" class="social" target="_blank">
          <div class="icon"><div class="footer-icon m-bible">&nbsp;</div></div>
        </a>
      </div>
      <div class="m-link-box">
        <a href="https://itunes.apple.com/us/podcast/calvary-monterey-audio/id216918040?mt=2&ign-mpt=uo%3D4" class="social" target="_blank">
          <div class="icon "><div class="footer-icon m-podcast">&nbsp;</div></div>
        </a>
      </div>
    </div>
  </div>

</br>
<div class="nav-buffer">&nbsp;</div>
</div>

app/views/home/_nav.html.erb
<nav id="main-nav" class="old-nav show-desktop">
  <div class="logo old-logo">&nbsp;</div>
  <div id="nav-wrap">
    <ul>
      <li>teachings</li>
      <li>books</li>
      <li>social</li>
      <li>about</li>
      <li>calvary</li>
      <li><a href="http://www.calvary.com/nateblog/" target="_blank">blog</a></li>
    </ul>
  </div>
</nav>
<nav id="main-nav-mobile" class="show-mobile">
  <div id="hamburger" class="fa fa-bars fa-2x">&nbsp;</div>
  <div id="mobile-links">
    <div class="mobile-link">teachings</div>
    <div class="mobile-link">books</div>
    <div class="mobile-link">social</div>
    <div class="mobile-link">about</div>
    <div class="mobile-link">calvary</div>
    <div class="mobile-link"><a href="http://www.calvary.com/nateblog/" target="_blank">blog</a></div>
  </div>
</nav>

app/views/home/_social.html.erb
<div>
  <h1 class="nice-header-1">Social</h1>
  <span id="social-link" style="margin-top:-100px;position:absolute;">&nbsp;</span>
  <br>
  <br>
  <br class="show-desktop">
  <div class="row">
    <div class="small-6 columns">
      <a href="https://facebook.com/nate.holdridge" class="social" target="_blank">
        <div class="icon social-icon"><i class="fa fa-facebook"></i></div>
      </a>
    </div>
    <div class="small-6 columns">
      <a href="https://twitter.com/nholdridge" class="social" target="_blank">
        <div class="icon social-icon"><i class="fa fa-twitter"></i></div>
      </a>
    </div>
  </div>
  <br>
  <br class="show-desktop">
  <br class="show-desktop">
  <br>
</div>

app/views/home/_spinner.html.erb
<div id="loader">
  <h3>LOADING</h3>
  <div class="spin">&nbsp;</div>
</div>

app/views/home/index.html.erb
<% if current_user %>
  <%= render "admin_links" %>
<% end %>

<div jc-teachings></div>
<div id="page-wrapper">
  <%= render "nav" %>
  <%= render "spinner" %>
  <%= render "bios" %>
  <%= render "biblebooks" %>
  <%= render "books" %>
  <%= render "social" %>
  <%= render "about" %>
  <%= render "calvary" %>
  <div id="player-wrapper" class="no-select">
    <div jc-player mp3=""></div>
    <div jc-player-controls show-progress="true"></div>
  </div>
</div>