config/routes.rb
Nate::Application.routes.draw do




  root to: "home#index"

  resources :biblebooks
  resources :teachings
  resources :users
  resources :sessions
  resources :bios
  resources :abouts
  resources :books
  resources :notes do
    resources :links
  end

  ### All for authentication ###
  get "log_out"  => "sessions#destroy", :as => "log_out"
  get "log_in"   => "sessions#new",     :as => "log_in"
  get "sign_up"  => "users#new",        :as => "sign_up"
  ##############################

end

app/models/biblebook.rb
class Biblebook < ActiveRecord::Base
  has_many :teachings, :order => "position ASC"


  has_attached_file :image,
    :styles => { :large => "400x400>", :medium => "240x240>", :thumb => "100x100>" },
    :storage => :s3,
    :s3_credentials => {
      :access_key_id => ENV['S3_KEY'],
      :secret_access_key => ENV['S3_SECRET'],
      :bucket => "nate_database"
    },
    :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
    :url => "/system/:attachment/:id/:style/:filename",
    :default_url => '/assets/missing_:style.jpg'
end

app/controllers/biblebooks_controller.rb
class BiblebooksController < ApplicationController
  before_action :set_biblebook, only: [:show, :edit, :update, :destroy]
  before_filter :authorize, except: [:show, :index]
  # GET /biblebooks
  # GET /biblebooks.json
  def index
    @biblebooks = Biblebook.all

    respond_to do |format|
      format.html
      format.json{ render json: @biblebooks, root: false}
    end
  end

  # GET /biblebooks/1
  # GET /biblebooks/1.json
  def show
    respond_to do |format|
      format.html
      format.json{ render json: @biblebook, root: false}
    end
  end

  # GET /biblebooks/new
  def new
    @biblebook = Biblebook.new
  end

  # GET /biblebooks/1/edit
  def edit
  end

  # POST /biblebooks
  # POST /biblebooks.json
  def create
    @biblebook = Biblebook.new(biblebook_params)

    respond_to do |format|
      if @biblebook.save
        format.html { redirect_to biblebooks_path, notice: 'Biblebook was successfully created.' }
        format.json { render action: 'show', status: :created, location: @biblebook }
      else
        format.html { render action: 'new' }
        format.json { render json: @biblebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /biblebooks/1
  # PATCH/PUT /biblebooks/1.json
  def update
    respond_to do |format|
      if @biblebook.update(biblebook_params)
        format.html { redirect_to biblebooks_path, notice: 'Biblebook was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @biblebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /biblebooks/1
  # DELETE /biblebooks/1.json
  def destroy
    @biblebook.destroy
    respond_to do |format|
      format.html { redirect_to biblebooks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_biblebook
      @biblebook = Biblebook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def biblebook_params
      params.require(:biblebook).permit(:name, :testament, :position, :image)
    end
end

app/views/biblebooks/_form.html.erb
<%= form_for @biblebook, :html => { :multipart => true } do |f| %>
  <% if @biblebook.errors.any? %>
    <div id="error_explanation small-12 columns">
      <h2><%= pluralize(@biblebook.errors.count, "error") %> prohibited this biblebook from being saved:</h2>

      <ul>
      <% @biblebook.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="large-4 small-12 columns">
    <h3><%= f.label :name %><br></h3>
    <%= f.text_field :name %>
  </div>
  <div class="large-4 small-12 columns">
    <h3><%= f.label "New testament ?" %><br></h3>
    <%= f.check_box :testament %>
  </div>
  <div class="large-4 small-12 columns">
    <h3><%= f.label :position %><br></h3>
    <%= f.number_field :position %>
  </div>


  <div class="large-4 small-12 columns">
    <h3><%= f.label :image %></h3>
    <%= f.file_field :image %>
  </div>
  <div class="large-4 small-12 columns">
    <h3>&nbsp;</h3>
    <h3><%= f.submit %></h3>
  </div>
<% end %>

app/views/biblebooks/edit.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>Editing biblebook</h1>
  </div>
  <%= render 'form' %>
  <div class="small-12 columns">
    <h3>&nbsp;</h3>
  </div>
  <div class="small-12 columns">
    <h3><%= link_to 'Back', @biblebook %></h3>
  </div>
</div>

app/views/biblebooks/index.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>Listing biblebooks</h1>
  </div>
  <div class="small-12 columns">
    <h3><%= link_to 'New biblebook', new_biblebook_path %></h3>
    <h3><%= link_to 'back', root_url %></h3>
  </div>
  <div class="small-12 columns">
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Position</th>
      </thead>

      <tbody>
        <% @biblebooks.each do |biblebook| %>
          <tr>
            <td><%= biblebook.name %></td>
            <td><%= biblebook.position %></td>
            <td><%= image_tag biblebook.image.url(:thumb)%></td>
            <td><%= link_to 'Edit', edit_biblebook_path(biblebook) %></td>
            <td><%= link_to 'Destroy', biblebook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/biblebooks/new.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>New biblebook</h1>
  </div>
  <%= render 'form' %>

  <div class="small-12 columns">
    <h3><%= link_to 'Back', biblebooks_path %></h3>
  </div>
</div>

app/views/biblebooks/new.js.erb
$('#new-link').hide().after('<%= j render("form") %>');

app/views/biblebooks/show.html.erb
<div id="loader">
  <h3>LOADING</h3>
  <div class="spin">&nbsp;</div>
</div>

<div class="js-black-background"></div>
<nav id="main-nav" class="new-nav">
  <h3 style="text-align:left;margin:8px 20px 6px;">
    <%= link_to "Back", root_url, class: "show-link" %>
  </h3>
</nav>
<div class="mobile-nav-buffer">&nbsp;</div>
<div class="mobile-show-header">
  <div class="mobile-cover-art"><%= image_tag @biblebook.image.url(:medium) %></div>
</div>
<div class="playlist-mobile">
  <% @biblebook.teachings.each do |teaching| %>
    <div class="teaching-item">
      <div class="play-this-teaching button-play-list-mobile" data-name="<%= teaching.name %>" data-mp3="<%= teaching.mp3 %>" data-refurl="<%= teaching.refurl %>" data-podcasturl="<%= teaching.podcasturl %>" data-biblebook="<%= teaching.biblebook.name %>">
        <div class="js-split">Chapter  <span class="mobile-teaching-name"><%= teaching.name %></span></div>
      </div>
    </div>
  <% end %>
</div>

<div id="player-wrapper" class="no-select" style="width:100%;">
  <div jc-player mp3=""></div>
  <div jc-player-controls show-progress="false"></div>
  <div jc-player-progress ></div>
</div>