config/routes.rb
Nate::Application.routes.draw do




  root to: "home#index"

  resources :biblebooks
  resources :teachings
  resources :users
  resources :sessions
  resources :bios
  resources :abouts
  resources :books
  resources :notes do
    resources :links
  end

  ### All for authentication ###
  get "log_out"  => "sessions#destroy", :as => "log_out"
  get "log_in"   => "sessions#new",     :as => "log_in"
  get "sign_up"  => "users#new",        :as => "sign_up"
  ##############################

end

app/models/teaching.rb
class Teaching < ActiveRecord::Base
  belongs_to :biblebook

  has_attached_file :mp3,
    :storage => :s3,
    :s3_credentials => {
      :access_key_id => ENV['S3_KEY'],
      :secret_access_key => ENV['S3_SECRET'],
      :bucket => "nate_database"
    },
    :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
    :url => "/system/:attachment/:id/:style/:filename",
    :default_url => '/assets/missing_:style.jpg'
end

app/controllers/teachings_controller.rb
class TeachingsController < ApplicationController
  before_action :set_teaching, only: [:show, :edit, :update, :destroy]
  before_filter :authorize

  # GET /teachings
  # GET /teachings.json
  def index
    @teachings = Teaching.all.order(params[:sort])
  end

  # GET /teachings/1
  # GET /teachings/1.json
  def show
  end

  # GET /teachings/new
  def new
    @teaching = Teaching.new
  end

  # GET /teachings/1/edit
  def edit
  end

  # POST /teachings
  # POST /teachings.json
  def create
    @teaching = Teaching.new(teaching_params)

    respond_to do |format|
      if @teaching.save
        format.html { redirect_to @teaching, notice: 'Teaching was successfully created.' }
        format.json { render action: 'show', status: :created, location: @teaching }
      else
        format.html { render action: 'new' }
        format.json { render json: @teaching.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachings/1
  # PATCH/PUT /teachings/1.json
  def update
    respond_to do |format|
      if @teaching.update(teaching_params)
        format.html { redirect_to @teaching, notice: 'Teaching was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @teaching.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachings/1
  # DELETE /teachings/1.json
  def destroy
    @teaching.destroy
    respond_to do |format|
      format.html { redirect_to teachings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teaching
      @teaching = Teaching.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teaching_params
      params.require(:teaching).permit(:name, :position, :biblebook_id, :mp3, :refurl, :podcasturl)
    end
end

app/views/teachings/_form.html.erb
<%= form_for @teaching, :html => { :multipart => true } do |f| %>
  <% if @teaching.errors.any? %>
    <div id="error_explanation small-12 columns">
      <h2><%= pluralize(@teaching.errors.count, "error") %> prohibited this teaching from being saved:</h2>

      <ul>
      <% @teaching.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="large-4 small-12 columns">
      <h3>Chapter</h3>
      <%= f.text_field :name %>
    </div>
    <div class="large-4 small-12 columns">
      <h3>Position</h3>
      <%= f.number_field :position %>
    </div>

    <div class="large-4 small-12 columns">
      <h3>Ref URL</h3>
      <%= f.text_field :refurl %>
    </div>

    <div class="large-4 small-12 columns">
      <h3>Podcast URL</h3>
      <%= f.text_field :podcasturl %>
    </div>

    <div class="large-4 small-12 columns">
      <h3>MP3</h3>
      <%= f.file_field :mp3 %>
    </div>

    <div class="large-4 small-12 columns">
      <h3>Biblebook</h3>
      <%= f.collection_select(:biblebook_id, Biblebook.all, :id, :name) %>
    </div>
    <div class="large-4 small-12 columns">

    </div>
  </div>
  <div class="row">
    <h3>&nbsp;</h3>
    <h3><%= f.submit %></h3>
  </div>
<% end %>

app/views/teachings/edit.html.erb
<h1>Editing teaching</h1>

<%= render 'form' %>
<div class="row">
  <h3><%= link_to 'Back', teachings_path %></h3>
</div>

app/views/teachings/index.html.erb
<div class="small-12 columns">
  <h1>Listing teachings</h1>
</div>
<div class="small-12 columns">
  <h3><%= link_to 'New Teaching', new_teaching_path %></h3>
  <h3><%= link_to 'back', root_url %></h3>
</div>
<div class="small-12 columns">
  <table>
    <thead>
      <tr>
        <th><%= link_to "Name", sort: "name" %></th>
        <th><%= link_to "Position", sort: "position" %></th>
        <th><%= link_to "Biblebook", sort: "biblebook_id" %></th>
        <th><%= link_to "Ref URL", sort: "refurl" %></th>
        <th><%= link_to "Podcast URL", sort: "podcasturl" %></th>
      </tr>
    </thead>

    <tbody>
      <% @teachings.each do |teaching| %>
        <tr>
          <td><%= teaching.name %></td>
          <td><%= teaching.position %></td>
          <td><% if teaching.biblebook.present? %><%= teaching.biblebook.name %></td><% end %>
          <td><%= teaching.refurl %></td>
          <td><%= teaching.podcasturl %></td>
          <td><%= link_to 'Edit', edit_teaching_path(teaching) %></td>
          <td><%= link_to 'Destroy', teaching, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/teachings/new.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>New teaching</h1>
  </div>
</div>
<%= render 'form' %>
<div class="row">
  <div class="small-12 columns">
    <h3><%= link_to 'Back', teachings_path %></h3>
  </div>
</div>

app/views/teachings/show.html.erb
<div class="row">
  <div class="small-12 columns">
    <p id="notice"><%= notice %></p>
  </div>
  <div class="small-12 columns">
    <p>
      <strong>Chapter:</strong>
      <%= @teaching.name %>
    </p>
    <p>
      <strong>Ref URL:</strong>
      <%= @teaching.refurl %>
    </p>
    <p>
      <strong>Podcast URL:</strong>
      <%= @teaching.podcasturl %>
    </p>
    <p>
      <strong>Position:</strong>
      <%= @teaching.position %>
    </p>

    <p>
      <strong>Biblebook:</strong>
      <%= @teaching.biblebook.name %>
    </p>
  </div>
  <div class="small-12 columns">

    <audio controls>
      <source src="<%= @teaching.mp3 %>" type="audio/ogg">
      <source src="<%= @teaching.mp3 %>" type="audio/mpeg">
    Your browser does not support the audio element.
    </audio>
  </div>
  <div class="small-12 columns">
    <h3><%= link_to 'Edit', edit_teaching_path(@teaching) %></h3>
    <h3><%= link_to 'Teachings', teachings_path %></h3>
    <h3><%= link_to 'New Teaching', new_teaching_path %></h3>
  </div>
</div>